name: GitHub Actions CI

on: [push, pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pylint
      - name: Analyzing the code with pylint
        run: |
          python3 -m pylint $(find ./ -type f | grep '\.py$' | xargs)
